SupFile2/Controllers/FileController.cs
using System;
using System.IO;
using System.Web.Mvc;
using SupFile2.Utilities;
using System.Configuration;
using SupFile2.Models;
using System.IO.Compression;
using SupFile2.Entities;
using System.Web;
using System.Linq;

namespace SupFile2.Controllers
{
    public class FileController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult AddFile()
        {
            var chemin = (string)MySession.GetChemin();
            HttpPostedFileBase file = Request.Files[0];
            //File will be saved in application root
            FileSystemItem fileSystemItem = FileSystemItem.GetElement((string)MySession.GetChemin(), MySession.GetUser().Id); // TODO check is session user is null
            bool result = fileSystemItem.CreateFile(file);

            return RedirectToAction("Index", "Home", new { Chemin = chemin });
        }


        public ActionResult Delete(String name)
        {
            var chemin = (string)MySession.GetChemin();
            string newPath = (string)MySession.GetChemin() + "/" + name;
            FileSystemItem fileSystemItem = FileSystemItem.GetElement(newPath, MySession.GetUser().Id); // TODO check if user is null
            bool result = fileSystemItem.Delete();
            return RedirectToAction("Index", "Home", new { Chemin = chemin });
        }
        public ActionResult Rename()
        {
            var name = Request.QueryString["filename"];
            string oldname = Request.QueryString["fileoldname"];
            string status = "nok";
            string newPath = (string)MySession.GetChemin() + "/" + oldname;
            FileSystemItem fileSystemItem = FileSystemItem.GetElement(newPath, MySession.GetUser().Id);
            bool result = fileSystemItem.Rename(name);
            if (result)
            {
                status = "ok";
            }
            return Content(status, "text/plain");
        }

        public ActionResult Download(String name)
        {
            var chemin = (string)MySession.GetChemin();
            FileSystemItem item = FileSystemItem.GetElement(chemin + "/" + name, MySession.GetUser().Id);
            FileInfo file = new FileInfo(Path.Combine(Debug.LocalStorage(), name));
            if (chemin != null)
            {
                file = new FileInfo(Path.Combine(Debug.LocalStorage(), chemin.ToString(), name));
            }
            if (file != null)
            {
                string pathFile = file.FullName;
                string nameFile = file.Name;
                string nameNoExt = nameFile.Split('.')[0];

                Response.Clear();
                Response.ContentType = "application/octet-stream";
                Response.AddHeader("Content-Disposition", "attachment; filename=" + nameFile);

                FileStream myFS = new FileStream(item.FilePath, FileMode.Open);
                MemoryStream myMS = new MemoryStream();
                myMS.SetLength(myFS.Length);
                myFS.Read(myMS.GetBuffer(), 0, (int)myFS.Length);
                myFS.Close();
                myMS.Flush();

                Response.BinaryWrite(myMS.ToArray());
                Response.Flush();

                myMS.Dispose();
                myMS.Close();

                Response.End();
            }

            return RedirectToAction("Index", "Home", new { Chemin = chemin });
        }

        public ActionResult Share(String name)
        {
            var chemin = (string)MySession.GetChemin();
            User myUser = (User)MySession.GetUser();

            string cheminFolder = string.Empty;
            if (chemin != null)
                cheminFolder += (string)MySession.GetChemin();
            cheminFolder += name;

            FileSystemItem fileSystemItem = FileSystemItem.GetElement(cheminFolder, myUser.Id);
            if (fileSystemItem != null)
            {
                if (fileSystemItem.Shared)
                {
                    fileSystemItem.Shared = false;
                }
                else
                {
                    fileSystemItem.Shared = true;
                }

                fileSystemItem.SetShare(fileSystemItem.Shared);
            }
            return RedirectToAction("Index", "Home", new { Chemin = chemin });
        }

        public ActionResult DisplayContent(String name)
        {
            var chemin = (string)MySession.GetChemin();
            FileInfo file = new FileInfo(Path.Combine(Debug.LocalStorage(), name));

            if (chemin != null)
            {
                file = new FileInfo(Path.Combine(Debug.LocalStorage(), chemin.ToString(), name));
            }

            if (file.Exists)
            {
                if (ViewerModel.ExtensionImage.ToList().Contains(file.Extension.ToLower()))
                {
                    return RedirectToAction("Index", "DisplayImage", new { Name = name });
                }

                else if (ViewerModel.ExtensionMovie.ToList().Contains(file.Extension.ToLower()))
                {
                    return RedirectToAction("Index", "DisplayMovie", new { Name = name });
                }

                else if (ViewerModel.ExtensionText.ToList().Contains(file.Extension.ToLower()))
                {
                    return RedirectToAction("Index", "DisplayText", new { Name = name });
                }
            }
            return RedirectToAction("Index", "Home", new { Chemin = chemin });
        }
    }
}

SupFile2/Controllers/FolderController.cs
using System;
using System.IO;
using System.Web.Mvc;

namespace SupFile2.Controllers
{
    using SupFile2.Entities;
    using SupFile2.Models;
    using SupFile2.Utilities;
    using System.Configuration;
    using System.IO.Compression;
    using System.Web.UI;

    public class FolderController : Controller
    {

        // GET: Folder
        public ActionResult AddFolder()
        {
            var name = Request.QueryString["foldername"];
            User myUser = (User)MySession.GetUser();
            FileSystemItem fileSystemItem = FileSystemItem.GetElement((string)MySession.GetChemin(), myUser.Id);
            bool result = fileSystemItem.createDirectory(name);
            String status = "nok";
            if(result)
            {
                status = "ok";
            }
            return Content(status, "text/plain");
        }
        public ActionResult Delete(String name)
        {
            var chemin = (string)MySession.GetChemin();
            string newPath = (string)MySession.GetChemin() + "/" + name;
            FileSystemItem fileSystemItem = FileSystemItem.GetElement(newPath, MySession.GetUser().Id);
            bool result = fileSystemItem.Delete();
            return RedirectToAction("Index", "Home", new { Chemin = chemin });
        }
        public ActionResult Rename()
        {
            // TODO check if session user is null
            var name = Request.QueryString["foldername"];
            string oldname = Request.QueryString["folderoldname"];
            string status = "nok";
            string newPath = (string)MySession.GetChemin() +"/" + oldname;
            FileSystemItem fileSystemItem = FileSystemItem.GetElement(newPath, MySession.GetUser().Id);
            bool result = fileSystemItem.Rename(name);
            if(result)
            {
                status = "ok";
            }
            return Content(status, "text/plain");
        }

        public ActionResult Download(String name)
        {
            var chemin = (string)MySession.GetChemin();
            User myUser = (User)MySession.GetUser();
            FileSystemItem fileSystemItem = FileSystemItem.GetElement(name, myUser.Id);
            if (fileSystemItem != null)
            {
                string pathFolder = fileSystemItem.Path;
                string nameFolder = fileSystemItem.Name;
                string nameNoExt = nameFolder.Split('.')[0];

                string startPath = @pathFolder + "\\" + nameNoExt + ".txt";
                string zipPath = @pathFolder + "\\" + nameNoExt + ".zip";


                if (!string.IsNullOrEmpty(zipPath))
                {
                    FileInfo zipFile = new FileInfo(Path.Combine(Debug.LocalStorage(), nameNoExt + ".zip"));
                    if (chemin != null)
                    {
                        zipFile = new FileInfo(Path.Combine(Debug.LocalStorage(), chemin.ToString(), nameNoExt + ".zip"));
                    }
                    if (zipFile.Exists)
                        zipFile.Delete();

                    ZipFile.CreateFromDirectory(startPath, zipPath, CompressionLevel.Fastest, true);

                    Response.Clear();
                    Response.ContentType = "application/octet-stream";
                    Response.AddHeader("Content-Disposition", "attachment; filename=" + nameFolder);

                    FileStream myFS = new FileStream(zipPath, FileMode.Open);
                    MemoryStream myMS = new MemoryStream();
                    myMS.SetLength(myFS.Length);
                    myFS.Read(myMS.GetBuffer(), 0, (int)myFS.Length);
                    myFS.Close();
                    myMS.Flush();

                    Response.BinaryWrite(myMS.ToArray());
                    Response.Flush();

                    myMS.Dispose();
                    myMS.Close();

                    Response.End();


                    FileInfo zipFile2 = new FileInfo(Path.Combine(Debug.LocalStorage(), nameNoExt + ".zip"));
                    if (chemin != null)
                    {
                        zipFile2 = new FileInfo(Path.Combine(Debug.LocalStorage(), chemin.ToString(), nameNoExt + ".zip"));
                    }
                    if (zipFile2.Exists)
                        zipFile2.Delete();
                }
            }

            return RedirectToAction("Index", "Home", new { Chemin = chemin });
        }

        public ActionResult Share(String name)
        {
            var chemin = (string)MySession.GetChemin();
            User myUser = (User)MySession.GetUser();
            
            string cheminFolder = string.Empty;
            if (chemin != null)
                cheminFolder += (string)MySession.GetChemin();
            cheminFolder += name;

            FileSystemItem fileSystemItem = FileSystemItem.GetElement(cheminFolder, myUser.Id);
            if (fileSystemItem != null)
            {
                if (fileSystemItem.Shared)
                {
                    //fileSystemItem.Shared = false;
                    fileSystemItem.SetShare(false);
                }
                else
                {
                    //fileSystemItem.Shared = true;
                    fileSystemItem.SetShare(true);
                    string lien = "https://localhost:44326/Home/DisplayFile?chemin=%2F" + cheminFolder + "&userName=" + myUser.Id.ToString();
                    string content = "<p>" + lien + "</p><br><a href=\"/\">Retour</a>";
                    return Content(content, "text/html");
                }

                fileSystemItem.SetShare(fileSystemItem.Shared);
            }
            return RedirectToAction("Index", "Home", new { Chemin = chemin });
        }
    }
}

SupFile2/Controllers/HomeController.cs
using System;
using System.IO;
using System.Web.Mvc;
using SupFile2.Utilities;

namespace SupFile2.Controllers
{
    using MySql.Data.MySqlClient;
    using SupFile2.Entities;
    using SupFile2.Models;
    using System.Collections.Generic;
    using System.Configuration;
    using System.Linq;
    using System.Web.UI.WebControls;

    public class HomeController : Controller
    {

        //[Route("Home/{*chemin}")]
        [Route("")]
        public ActionResult Index(String c, String u)
        {
            string chemin = Request.QueryString["chemin"];
            string userName = Request.QueryString["userName"];

            if (chemin == "DisplayFile")
            {
                return Redirect("DisplayFile");
            }
            User user = MySession.GetUser();
            if (user != null)
            {
                StorageManager sManager = StorageManager.Instance;
                var userStockageFree = user.StockageMax - user.Stockage;

                MySession.SetChemin(chemin);

                FileSystemItem fsi = FileSystemItem.GetElement(chemin, user.Id);
                if (!fsi.IsDir)
                {
                    return RedirectToAction("DisplayFile");
                }

                FileSystemItem[] items = fsi.Getchilds().ToArray();
                items = items.Where(i => i.UserId == user.Id).ToArray();
                ViewBag.User = user;
                ViewBag.Items = items;
                ViewBag.Chemin = chemin;
                ViewBag.UserStockage = sManager.KilobyteToGygabyte(userStockageFree);
                
                return View();
            }
            else if (!string.IsNullOrEmpty(chemin) && !string.IsNullOrEmpty(userName))
            {
                MySession.SetChemin(chemin);

                FileSystemItem fsi = FileSystemItem.GetElement(chemin, Int32.Parse(userName));
                FileSystemItem[] items = fsi.Getchilds().Where(i => i.Shared).ToArray();

                if (items != null && items.Count() > 0)
                {
                    ViewBag.Items = items;
                    ViewBag.Chemin = chemin;

                    return View();
                }
                else if (fsi.IsDir)
                {
                    ViewBag.Items = items;
                    ViewBag.Chemin = chemin;
                    return View();
                }
                else
                    return RedirectToAction("Index", "LandingPage");
            }
            else
            {
                return RedirectToAction("Index", "LandingPage");
            }
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        /*public ActionResult DisplayFile(String chemin)
        {
            //string chemin = MySession.GetChemin() as string;
            FileSystemItem fsi = FileSystemItem.GetElement(chemin, MySession.GetUser().Id);
            ViewBag.Chemin = fsi.Filename;
            return View();*/

        public ActionResult DisplayFile()
        {
            string chemin = Request.QueryString["chemin"];
            int userId;
            if (Request.QueryString["userName"] == null)
                userId = MySession.GetUser().Id;
            else
                userId = int.Parse(Request.QueryString["userName"]);

            FileSystemItem fsi = FileSystemItem.GetElement(chemin, userId);
            bool logged = MySession.GetUser() != null;
            if (logged) logged = MySession.GetUser().Id == fsi.UserId;
            if (fsi != null && (fsi.Shared || logged))
            {
                ViewBag.Chemin = fsi.Path;
                ViewBag.FileName = fsi.Name;
                ViewBag.UserId = fsi.UserId;

                switch(fsi.Extension.ToLower())
                {
                    case "png":
                    case "jpeg":
                    case "jpg":
                        ViewBag.Type = "image";
                        break;
                    case "mp4":
                        ViewBag.Type = "video";
                        break;
                    case "mp3":
                        ViewBag.Type = "audio";
                        break;
                }

                if (ViewBag.Type == null) return RedirectToAction("Index", "LandingPage");
                return View();
            }
            return RedirectToAction("Index", "LandingPage");
        }

        public ActionResult GetFile()
        {
            string chemin = Request.QueryString["chemin"]; // TODO fix
            int userId;
            if (Request.QueryString["userName"] == null)
                userId = MySession.GetUser().Id;
            else
                userId = int.Parse(Request.QueryString["userName"]);

            FileSystemItem fsi = FileSystemItem.GetElement(chemin, userId);
            if (fsi == null) return RedirectToAction("Index", "LandingPage");
            
            FileInfo file = new FileInfo(fsi.FilePath);
            if (file != null)
            {
                Response.Clear();
                Response.ContentType = "application/octet-stream";
                Response.AddHeader("Content-Disposition", "attachment; filename=" + fsi.Name);

                FileStream myFS = new FileStream(fsi.FilePath, FileMode.Open);
                MemoryStream myMS = new MemoryStream();
                myMS.SetLength(myFS.Length);
                myFS.Read(myMS.GetBuffer(), 0, (int)myFS.Length);
                myFS.Close();
                myMS.Flush();

                Response.BinaryWrite(myMS.ToArray());
                Response.Flush();

                myMS.Dispose();
                myMS.Close();

                Response.End();
            }
            return null;
        }

        public bool IsSharedFile(string id)
        {
            string sql = "SELECT COUNT(*) as exists FROM `share` WHERE ";
            sql += "`share.id` LIKE '" + id + ";";

            MySqlCommand command = Database.Instance.Connection.CreateCommand();
            command.CommandText = sql;
            MySqlDataReader reader = command.ExecuteReader();

            bool result = false;
            while (reader.Read())
            {
                result = reader.GetInt32("exists") > 0;
            }
            reader.Close();

            return result;
        }

    }
}

SupFile2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";

}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SupFile2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SupFile2/Views/Home/DisplayFile.cshtml
@{
    ViewBag.Title = "Visualisation";
}

<h2>@ViewBag.FileName</h2>
@if (ViewBag.Type == "image")
{
    <img src="/Home/GetFile?chemin=@ViewBag.Chemin&userName=@ViewBag.UserId"/>
}
else if (ViewBag.Type == "video")
{
    <video controls>
        <source src="/Home/GetFile?chemin=@ViewBag.Chemin&userName=@ViewBag.UserId" />
    </video>
}
else if (ViewBag.Type == "audio")
{
    <audio controls>
        <source src="/Home/GetFile?chemin=@ViewBag.Chemin&userName=@ViewBag.UserId" />
    </audio>
}

SupFile2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";

}

<div class="col-sm-2">
    <a href="#" onclick='addFolder()' class="glyphicon glyphicon-plus addBtn"> Ajouter un dossier </a>
    <a href="#" onclick='addFile()' class="glyphicon glyphicon-plus addBtn"> Ajouter un fichier </a>
</div>
<div class="col-sm-8">
    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th class="table-title col-sm-1"></th>
                <th class="table-title col-sm-2">Nom</th>
                <th class="table-title col-sm-2">Taille</th>
                <th class="table-title col-sm-2">Membres</th>
                <th class="table-title col-sm-2">Action</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in ViewBag.Items)
            {
                <tr>
                    @if (item.IsDir)
                    {
                        <td><img class="itemLogo" src="/Content/images/folderlogo.png" /></td>
                        <td><a href="@Url.Action("Index", "Home", new { chemin = @item.Path})"><p class="folderName">@item.Name</p></a></td>
                        <td></td>

                        if (@item.Shared)
                        {
                            <td>
                                Public
                            </td>
                        }

                        else
                        {
                            <td>
                                Privé
                            </td>
                        }
                        <td>
                            <div class="btn-group">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">

                                    <span class="glyphicon glyphicon-chevron-down"></span>
                                </a>
                                <ul class="dropdown-menu pull-left" role="menu" aria-labelledby="dropdownMenu">
                                    <li><a class="glyphicon glyphicon-trash" href="@Url.Action("Delete", "Folder", new { name = item.Name })"> Supprimer</a></li>
                                    <li><a class="glyphicon glyphicon-pencil" href="#" onclick='renameFolder("@item.Name")'> Renommer </a></li>
                                    <li><a class="glyphicon glyphicon-download-alt" href="@Url.Action("Download", "Folder", new { name = item.Name })"> Télécharger (format zip) </a></li>
                                    <li>
                                        @if (@item.Shared)
                                        {
                                            <a class="glyphicon glyphicon-share-alt" href="@Url.Action("Share", "Folder", new { name = item.Name })"> Ne pas partager </a>
                                        }
                                        else
                                        {
                                            <a class="glyphicon glyphicon-share-alt" href="@Url.Action("Share", "Folder", new { name = item.Name })"> Partager </a>
                                        }
                                    </li>
                                </ul>
                            </div>

                        </td>





                    }
                    else
                    {
                        <td><img class="itemLogo" src="/Content/images/filelogo.png" /></td>

                        <!--<td><a href="@Url.Action("DisplayFile", "Home", new { chemin = @item.Path})"><p class="fileName">@item.Name</p></a></td>-->

                        <td><a href="@Url.Action("DisplayFile", "Home", new { chemin = @item.Path, user = @item.UserId })"><p class="fileName">@item.Name</p></a></td>

                        <td>@item.Size Ko</td>
                        if (@item.Shared)
                        {
                            <td>
                                Publicmm
                            </td>
                        }

                        else
                        {
                            <td>
                                Privé
                            </td>
                        }
                        <td>
                            <div class="btn-group">
                                <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">

                                    <span class="glyphicon glyphicon-chevron-down"></span>
                                </a>
                                <ul class="dropdown-menu pull-left" role="menu" aria-labelledby="dropdownMenu">
                                    <li><a class="glyphicon glyphicon-trash" href="@Url.Action("Delete", "File", new { name = item.Name })"> Supprimer</a></li>
                                    <li><a class="glyphicon glyphicon-pencil" href="#" onclick='renameFile("@item.Name")'> Renommer </a></li>
                                    <li><a class="glyphicon glyphicon-download-alt" href="@Url.Action("Download", "File", new { name = item.Name })"> Télécharger </a></li>
                                    <li>
                                        @if (@item.Shared)
                                        {
                                            <a class="glyphicon glyphicon-share-alt" href="@Url.Action("Share", "File", new { name = item.Name })"> Ne pas partager </a>
                                        }
                                        else
                                        {
                                            <a class="glyphicon glyphicon-share-alt" href="@Url.Action("Share", "File", new { name = item.Name })"> Partager </a>
                                        }
                                    </li>
                                </ul>
                            </div>

                        </td>


                    }

                </tr>
            }
        </tbody>
        <!--<tfoot>
            <tr>
                <th class="table-title"></th>
                <th class="table-title">Name</th>
                <th class="table-title">Taille</th>
                <th class="table-title col-sm-2">Membres</th>
                <th class="table-title">Action</th>
            </tr>
        </tfoot>-->
    </table>
</div>
<div class="col-sm-2">
    <p class="table-title"> Espaces libre :</p>
    @ViewBag.UserStockage Go
</div>